# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SpotlightRevised' do
pod 'LLSimpleCamera', '~> 4.1'
end

target 'SpotlightRevisedTests' do

end

target 'SpotlightRevisedUITests' do

end

